export const GREEK_WORDS = {
  love: [
    {
      greek: 'ἀγάπη',
      transliteration: 'agapē',
      strongs: 'G26',
      definition: "Unconditional, self-sacrificial love — the highest form of love; God's love for humanity and the love commanded between believers.",
      etymology: "From agapaō (to prefer, to choose). Distinguished from erōs (desire) and philia (friendship).",
      frequency: 143,
      testament: 'NT',
    },
    {
      greek: 'φιλέω',
      transliteration: 'phileō',
      strongs: 'G5368',
      definition: 'Brotherly affection, fondness, warmth — the love of friendship and family.',
      etymology: 'From philos (friend/dear). Relates to philadelphia (brotherly love) and philanthrōpia (love of humanity).',
      frequency: 25,
      testament: 'NT',
    },
    {
      greek: 'ἔρως',
      transliteration: 'erōs',
      strongs: '—',
      definition: "Romantic or passionate desire. Notably absent from the New Testament — Paul deliberately avoids it.",
      etymology: "From eraō (to desire intensely). Root of English 'erotic.' Its absence in the NT is theologically significant.",
      frequency: 0,
      testament: 'NT',
    },
    {
      greek: 'אַהֲבָה',
      transliteration: 'ahavah',
      strongs: 'H160',
      definition: "The primary Hebrew word for love — encompasses love between people, love of God, and love of objects.",
      etymology: "From ahav (to love, to have affection). Used for God's covenant love and human love.",
      frequency: 40,
      testament: 'OT',
    },
    {
      greek: 'חֶסֶד',
      transliteration: 'hesed',
      strongs: 'H2617',
      definition: "Covenant love, lovingkindness, steadfast mercy — God's faithful love rooted in covenant relationship.",
      etymology: "Often translated 'lovingkindness' or 'steadfast love.' Core to God's character in the OT.",
      frequency: 248,
      testament: 'OT',
    },
  ],
  faith: [
    {
      greek: 'πίστις',
      transliteration: 'pistis',
      strongs: 'G4102',
      definition: "Faith, belief, trust — both the act of believing and the content believed. In Paul, the foundational means of justification.",
      etymology: 'From peitho (to persuade, to trust). Pistis means both subjective faith and objective faithfulness.',
      frequency: 243,
      testament: 'NT',
    },
    {
      greek: 'אֱמוּנָה',
      transliteration: 'emunah',
      strongs: 'H530',
      definition: 'Faithfulness, steadfastness, trustworthiness — the OT root of NT faith. "The just shall live by his emunah" (Hab 2:4).',
      etymology: "From aman (to be firm, to support). Root of 'amen' — what is firm and reliable.",
      frequency: 49,
      testament: 'OT',
    },
  ],
  grace: [
    {
      greek: 'χάρις',
      transliteration: 'charis',
      strongs: 'G5485',
      definition: "Grace, favor — God's unmerited favor toward sinners. The foundational concept of the gospel in Paul's letters.",
      etymology: 'From chairō (to rejoice, to be glad). Charis gives freely, without obligation or debt.',
      frequency: 156,
      testament: 'NT',
    },
    {
      greek: 'חֵן',
      transliteration: 'chen',
      strongs: 'H2580',
      definition: "Grace, favor — finding favor in the eyes of someone greater. 'Noah found chen in the eyes of the LORD.'",
      etymology: "From chanan (to be gracious, to show favor). Related to channah (Hannah — 'grace').",
      frequency: 69,
      testament: 'OT',
    },
  ],
  peace: [
    {
      greek: 'εἰρήνη',
      transliteration: 'eirēnē',
      strongs: 'G1515',
      definition: "Peace — not merely absence of conflict, but wholeness, harmony, and well-being. The peace Christ gives 'surpasses understanding.'",
      etymology: 'From eirō (to join). Influenced by Hebrew shalom — fullness rather than just cessation of conflict.',
      frequency: 92,
      testament: 'NT',
    },
    {
      greek: 'שָׁלוֹם',
      transliteration: 'shalom',
      strongs: 'H7965',
      definition: 'Peace, wholeness, completeness — the comprehensive well-being of individuals, communities, and nations in right relationship.',
      etymology: 'From shalam (to be complete, to be sound). Encompasses health, prosperity, safety, and relational harmony.',
      frequency: 237,
      testament: 'OT',
    },
  ],
  spirit: [
    {
      greek: 'πνεῦμα',
      transliteration: 'pneuma',
      strongs: 'G4151',
      definition: 'Spirit, breath, wind — the divine Spirit (Holy Spirit), the human spirit, and angelic beings. Context determines meaning.',
      etymology: 'From pneō (to breathe, to blow). Same root as pneumonia. Wind and breath are the visible signs of invisible spirit.',
      frequency: 385,
      testament: 'NT',
    },
    {
      greek: 'רוּחַ',
      transliteration: 'ruach',
      strongs: 'H7307',
      definition: "Spirit, wind, breath — 'The Spirit of God was hovering over the waters' (Gen 1:2). The animating breath of life.",
      etymology: 'From ruach (to breathe, to blow). Appears first in Genesis 1:2. Also means the wind.',
      frequency: 378,
      testament: 'OT',
    },
  ],
  hope: [
    {
      greek: 'ἐλπίς',
      transliteration: 'elpis',
      strongs: 'G1680',
      definition: "Hope — not wishful thinking but confident expectation of what God has promised. The anchor of the soul (Heb 6:19).",
      etymology: "From elpō (to anticipate). Biblical hope is certain (God's promise), unlike human hope (mere possibility).",
      frequency: 53,
      testament: 'NT',
    },
    {
      greek: 'תִּקְוָה',
      transliteration: 'tiqvah',
      strongs: 'H8615',
      definition: "Hope, expectation, cord — the 'scarlet cord' (tiqvah) in Rahab's window (Josh 2:18) is the same word as hope.",
      etymology: 'From qavah (to wait, to expect). The cord image: hope as a lifeline you hold onto.',
      frequency: 34,
      testament: 'OT',
    },
  ],
  light: [
    {
      greek: 'φῶς',
      transliteration: 'phōs',
      strongs: 'G5457',
      definition: "Light — physical light, divine light, and moral/spiritual enlightenment. 'God is light; in him is no darkness at all' (1 John 1:5).",
      etymology: 'From phainō (to shine). Root of photography, phosphorus, phenomenon. Opposite: skotia (darkness).',
      frequency: 73,
      testament: 'NT',
    },
    {
      greek: 'אוֹר',
      transliteration: 'or',
      strongs: 'H216',
      definition: "Light — the first creation ('Let there be light,' Gen 1:3). Both physical light and God's revelation and salvation.",
      etymology: "From or (to be or become light). Used for the light of Torah: 'Your word is a lamp… and a light to my path' (Ps 119:105).",
      frequency: 120,
      testament: 'OT',
    },
  ],
  truth: [
    {
      greek: 'ἀλήθεια',
      transliteration: 'alētheia',
      strongs: 'G225',
      definition: "Truth — reality as opposed to appearance; divine disclosure. 'I am the way, the truth, and the life' (John 14:6).",
      etymology: "From a- (not) + lēthē (hidden/forgotten). Truth is what is 'un-hidden' — the disclosure of reality.",
      frequency: 109,
      testament: 'NT',
    },
    {
      greek: 'אֱמֶת',
      transliteration: 'emet',
      strongs: 'H571',
      definition: "Truth, reliability, faithfulness — truth as that which is firm and enduring. God's truth is his reliable character.",
      etymology: 'From aman (to be firm, to be reliable). Related to amen. The three letters aleph-mem-tav encompass the Hebrew alphabet.',
      frequency: 127,
      testament: 'OT',
    },
  ],
  gospel: [
    {
      greek: 'εὐαγγέλιον',
      transliteration: 'euangelion',
      strongs: 'G2098',
      definition: "Good news, gospel — the announcement of victory in the ancient world. In NT: the announcement that God has acted decisively in Jesus Christ.",
      etymology: "From eu (good) + angelos (messenger). An euangelos was a herald announcing military victory. Root of 'evangelical.'",
      frequency: 76,
      testament: 'NT',
    },
  ],
  word: [
    {
      greek: 'λόγος',
      transliteration: 'logos',
      strongs: 'G3056',
      definition: "Word, reason, logic — the rational principle behind all creation. 'In the beginning was the Logos' (John 1:1). Jesus IS the Word.",
      etymology: 'From legō (to speak, to lay out). In Greek philosophy: the rational principle of the cosmos. John redefines it as personal.',
      frequency: 330,
      testament: 'NT',
    },
    {
      greek: 'ῥῆμα',
      transliteration: 'rhēma',
      strongs: 'G4487',
      definition: "Spoken word, utterance — the specific word spoken in a moment. Distinct from logos (the enduring Word). 'Man shall not live by bread alone but by every rhēma of God' (Matt 4:4).",
      etymology: 'From rheō (to speak, to flow). An individual spoken word or statement, vs. logos which is the broader concept.',
      frequency: 68,
      testament: 'NT',
    },
    {
      greek: 'דָּבָר',
      transliteration: 'dabar',
      strongs: 'H1697',
      definition: "Word, thing, matter — the Hebrew dabar is both the spoken word and the event it creates. God's dabar is performative: it does what it says.",
      etymology: "From dabar (to speak, to drive forward). 'Dabar' also means 'thing' — Hebrew sees word and deed as inseparable.",
      frequency: 1440,
      testament: 'OT',
    },
  ],

  // ── NEW WORDS ──────────────────────────────────────────────

  salvation: [
    {
      greek: 'σωτηρία',
      transliteration: 'sōtēria',
      strongs: 'G4991',
      definition: "Salvation, deliverance, rescue — God's comprehensive act of rescuing humanity from sin, death, and judgment. Encompasses past justification, present sanctification, and future glorification.",
      etymology: "From sōzō (to save, to heal, to rescue). Related to sōtēr (Savior) and sōma (body). Health and rescue are the same root — salvation is holistic.",
      frequency: 45,
      testament: 'NT',
    },
    {
      greek: 'יְשׁוּעָה',
      transliteration: 'yeshuah',
      strongs: 'H3444',
      definition: "Salvation, deliverance, victory — God's saving action in history. The name 'Jesus' (Yeshua) IS this word: 'You shall call his name Yeshua, for he will save his people.'",
      etymology: "From yasha (to save, to deliver). Yeshua/Joshua/Jesus are all forms of this root. The name IS the mission.",
      frequency: 78,
      testament: 'OT',
    },
  ],
  redemption: [
    {
      greek: 'ἀπολύτρωσις',
      transliteration: 'apolytrōsis',
      strongs: 'G629',
      definition: "Redemption, release, ransom payment — the act of buying someone out of slavery or captivity. In NT: Christ's death as the price that frees humanity from sin's bondage.",
      etymology: "From apo (from) + lyō (to loose) + tron (price of release). A marketplace term: the purchase price that sets a slave free.",
      frequency: 10,
      testament: 'NT',
    },
    {
      greek: 'גָּאַל',
      transliteration: 'ga\'al',
      strongs: 'H1350',
      definition: "To redeem, to act as kinsman-redeemer — the go'el was the nearest male relative who had both the right and duty to redeem family members from slavery or debt. Boaz redeemed Ruth.",
      etymology: "Root: ga'al (to redeem, to reclaim). The go'el kinsman-redeemer is the OT archetype for Christ's redemptive work.",
      frequency: 104,
      testament: 'OT',
    },
    {
      greek: 'פָּדָה',
      transliteration: 'padah',
      strongs: 'H6299',
      definition: "To ransom, to redeem by price — distinct from ga'al (kinship redemption), padah emphasizes the payment of a price. Used for Israel's exodus: God 'ransomed' them from Egypt.",
      etymology: "From padah (to cut off, to ransom). Emphasizes the cost and transaction of redemption.",
      frequency: 59,
      testament: 'OT',
    },
  ],
  righteousness: [
    {
      greek: 'δικαιοσύνη',
      transliteration: 'dikaiosynē',
      strongs: 'G1343',
      definition: "Righteousness, justice, right standing — both God's own righteous character and the status of 'right standing' he declares over believers. The great exchange: Christ's dikaiosynē credited to sinners.",
      etymology: "From dikaios (just, righteous) + synē (quality). Dikaios comes from dikē (right, custom, justice). Not merely moral behavior — a legal standing before God.",
      frequency: 92,
      testament: 'NT',
    },
    {
      greek: 'צְדָקָה',
      transliteration: 'tsedaqah',
      strongs: 'H6666',
      definition: "Righteousness, justice, right action — both God's attribute and the human conduct that flows from covenant relationship. Inseparable from social justice: caring for the poor IS tsedaqah.",
      etymology: "From tsadeq (to be right, to be just). In Hebrew thought, righteousness is relational and social, not just moral purity.",
      frequency: 157,
      testament: 'OT',
    },
  ],
  mercy: [
    {
      greek: 'ἔλεος',
      transliteration: 'eleos',
      strongs: 'G1656',
      definition: "Mercy, compassion — kindness shown to the suffering, helpless, or guilty. Contrasted with strict justice. The cry 'Kyrie eleison' ('Lord, have mercy') is the oldest Christian prayer.",
      etymology: "From eleeō (to show mercy). Related to the Hebrew hesed. In LXX (Septuagint), eleos often translates hesed — linking NT mercy to OT covenant faithfulness.",
      frequency: 27,
      testament: 'NT',
    },
    {
      greek: 'רַחֲמִים',
      transliteration: 'rachamim',
      strongs: 'H7356',
      definition: "Tender mercies, compassion — from the word for 'womb' (rechem). God's mercy is visceral, gut-level love: the feeling a mother has for the child of her womb.",
      etymology: "From rechem (womb). Plural form indicates intensity. When God 'has compassion,' it is like a mother's love — instinctive, fierce, unconditional.",
      frequency: 39,
      testament: 'OT',
    },
  ],
  covenant: [
    {
      greek: 'διαθήκη',
      transliteration: 'diathēkē',
      strongs: 'G1242',
      definition: "Covenant, testament, will — a binding agreement, but unlike a contract it is initiated and guaranteed by the stronger party. The 'new covenant' (Jer 31/Luke 22) is God's unilateral commitment.",
      etymology: "From diatithēmi (to arrange, to dispose). In Greek law: a will or testament that only the maker can alter. Emphasizes God's initiative, not mutual negotiation.",
      frequency: 33,
      testament: 'NT',
    },
    {
      greek: 'בְּרִית',
      transliteration: 'berit',
      strongs: 'H1285',
      definition: "Covenant — the foundational OT concept for God's relationship with humanity. Sealed by sacrifice, blood, and an oath. God makes berits with Noah, Abraham, Moses, David, and ultimately all humanity.",
      etymology: "Possibly from bara (to cut) — covenants were sealed by 'cutting' animals in half (Gen 15). The parties walked between the pieces, invoking the same fate if they broke faith.",
      frequency: 284,
      testament: 'OT',
    },
  ],
  forgiveness: [
    {
      greek: 'ἄφεσις',
      transliteration: 'aphesis',
      strongs: 'G859',
      definition: "Forgiveness, release, remission — the complete cancellation of a debt or offense. Not just 'overlooking' sin but its legal cancellation. 'Your sins are forgiven' is a declaration of aphesis.",
      etymology: "From aphiēmi (to send away, to release). The picture: sin as a debt sent away, never to return. Related to the Year of Jubilee when debts were cancelled.",
      frequency: 17,
      testament: 'NT',
    },
    {
      greek: 'סְלִיחָה',
      transliteration: 'selichah',
      strongs: 'H5547',
      definition: "Forgiveness, pardon — God's sovereign act of releasing the guilty from punishment. 'But with you there is selichah, so that you may be feared' (Ps 130:4).",
      etymology: "From salach (to forgive, to pardon). Unlike human forgiveness, selichah is exclusively God's — only God forgives in this ultimate sense.",
      frequency: 3,
      testament: 'OT',
    },
  ],
  glory: [
    {
      greek: 'δόξα',
      transliteration: 'doxa',
      strongs: 'G1391',
      definition: "Glory, honor, splendor — the visible manifestation of God's presence and worth. Originally meant 'opinion/reputation' in Greek; Scripture transforms it to mean God's radiating weightiness and beauty.",
      etymology: "From dokeō (to seem, to think). Transformed in LXX to translate kabod — God's glory redefined Greek opinion as divine weight and magnificence.",
      frequency: 166,
      testament: 'NT',
    },
    {
      greek: 'כָּבוֹד',
      transliteration: 'kabod',
      strongs: 'H3519',
      definition: "Glory, weight, honor — God's presence made visible and felt. The kabod Yahweh filled the tabernacle and temple. Its root is 'heavy' — glory has weight, substance, reality.",
      etymology: "From kaved (to be heavy, to be weighty). Glory is the opposite of emptiness. The Shekinah cloud-pillar that led Israel is kabod made visible.",
      frequency: 200,
      testament: 'OT',
    },
  ],
  kingdom: [
    {
      greek: 'βασιλεία',
      transliteration: 'basileia',
      strongs: 'G932',
      definition: "Kingdom, reign, rule — primarily the dynamic rule or kingship of God, not just a geographic territory. The central theme of Jesus' preaching: the kingdom is both present ('already') and future ('not yet').",
      etymology: "From basileus (king). Emphasizes active reign, not just realm. 'The kingdom of God is at hand' means God's rule is breaking into history now.",
      frequency: 162,
      testament: 'NT',
    },
    {
      greek: 'מַלְכוּת',
      transliteration: 'malkuth',
      strongs: 'H4438',
      definition: "Kingdom, reign, royal rule — the sovereign dominion of God. Daniel's vision of the malkuth of God that will never be destroyed contrasts with all human empires.",
      etymology: "From melek (king). In Daniel, malkuth is used for both earthly kingdoms and the eternal kingdom of God that supersedes them all.",
      frequency: 91,
      testament: 'OT',
    },
  ],
  sin: [
    {
      greek: 'ἁμαρτία',
      transliteration: 'hamartia',
      strongs: 'G266',
      definition: "Sin, missing the mark — an archery term: the arrow that misses the target. In NT: not just individual acts but the power that holds humanity in bondage. 'Sin' (singular) is a slave master.",
      etymology: "From hamartanō (to miss, to fail). Originally: an arrow that misses. Aristotle used it for a tragic flaw. Paul deepens it: sin as a reigning power, not just a mistake.",
      frequency: 173,
      testament: 'NT',
    },
    {
      greek: 'חֵטְא',
      transliteration: 'chet',
      strongs: 'H2399',
      definition: "Sin, missing the mark — the most common OT word for sin. Used for both unintentional and deliberate offenses. The Day of Atonement addresses chet as the primary problem between God and Israel.",
      etymology: "From chata (to miss, to go wrong). Same archery/path metaphor as NT hamartia. Sin is missing the target God intends for human life.",
      frequency: 296,
      testament: 'OT',
    },
    {
      greek: 'פֶּשַׁע',
      transliteration: 'pesha',
      strongs: 'H6588',
      definition: "Transgression, rebellion — deliberate defiance; going beyond the boundary. Stronger than chet. Used of willful, knowing rebellion against God's authority.",
      etymology: "From pasha (to rebel, to break away). Political rebellion language: a vassal refusing to submit to the king. Sin as insurrection.",
      frequency: 93,
      testament: 'OT',
    },
  ],
  resurrection: [
    {
      greek: 'ἀνάστασις',
      transliteration: 'anastasis',
      strongs: 'G386',
      definition: "Resurrection, rising up — the bodily rising from the dead. Not resuscitation (returning to mortal life) but transformation into an immortal body. Christ's anastasis is the firstfruit guaranteeing all believers' future resurrection.",
      etymology: "From ana (up) + stasis (standing). Literally: a standing up again. Against Greek body-soul dualism, anastasis affirms the body's permanent importance.",
      frequency: 42,
      testament: 'NT',
    },
    {
      greek: 'תְּחִיָּה',
      transliteration: 'techiyyah',
      strongs: 'H8467',
      definition: "Revival, restoration to life — the OT concept anticipating full resurrection. Ezekiel's valley of dry bones (37:1-14) is the most vivid OT picture of corporate resurrection.",
      etymology: "From chayah (to live, to revive). The valley of dry bones shows God's power to restore what is completely dead — applied first to Israel, then to final resurrection.",
      frequency: 1,
      testament: 'OT',
    },
  ],
  wisdom: [
    {
      greek: 'σοφία',
      transliteration: 'sophia',
      strongs: 'G4678',
      definition: "Wisdom — both human skill/discernment and divine wisdom. In Paul, Christ IS the sophia of God (1 Cor 1:24), inverting Greek philosophical wisdom. God's 'foolishness' (the cross) is wiser than human sophia.",
      etymology: "From sophos (skilled, wise). Greek philosophy prized sophia above all virtues. Paul subverts this: the cross appears foolish but IS the wisdom of God.",
      frequency: 51,
      testament: 'NT',
    },
    {
      greek: 'חָכְמָה',
      transliteration: 'chokmah',
      strongs: 'H2451',
      definition: "Wisdom — practical skill for living well in God's creation. Not abstract knowledge but applied understanding. Personified in Proverbs 8 as present with God at creation, calling humanity.",
      etymology: "From chakam (to be wise, to be skilled). A craftsman has chokmah in their craft. Wisdom is skill for living, not just intellectual knowledge.",
      frequency: 149,
      testament: 'OT',
    },
  ],
  holy: [
    {
      greek: 'ἅγιος',
      transliteration: 'hagios',
      strongs: 'G40',
      definition: "Holy, set apart, consecrated — the fundamental nature of God and the calling of his people. Not primarily 'morally pure' but 'other' — belonging to a different order of reality. 'Be hagios, because I am hagios.'",
      etymology: "From hagos (awe, sacred thing). Separated from the ordinary. The Holy of Holies was the most hagios place because it was most fully God's space.",
      frequency: 233,
      testament: 'NT',
    },
    {
      greek: 'קָדוֹשׁ',
      transliteration: 'qadosh',
      strongs: 'H6918',
      definition: "Holy, separate, set apart — the defining attribute of God in the OT. The Trisagion ('Holy, holy, holy,' Isa 6:3) is the angels' cry before the throne. To be holy is to be separated unto God.",
      etymology: "From qadash (to set apart, to consecrate). Holiness begins with God's otherness: he is utterly unlike creation. Called things and people 'participate' in God's holiness.",
      frequency: 116,
      testament: 'OT',
    },
  ],
  repentance: [
    {
      greek: 'μετάνοια',
      transliteration: 'metanoia',
      strongs: 'G3341',
      definition: "Repentance, change of mind/direction — far more than feeling sorry. A complete reorientation of thinking, values, and direction. John the Baptist and Jesus both opened with metanoia as the first step into the kingdom.",
      etymology: "From meta (after, change) + nous (mind). A mind that has changed direction: turned around, not just remorseful. Metanoia is a U-turn, not just regret.",
      frequency: 22,
      testament: 'NT',
    },
    {
      greek: 'שׁוּב',
      transliteration: 'shub',
      strongs: 'H7725',
      definition: "To return, to turn back — the OT concept of repentance. Israel is called to 'return to the LORD.' The prodigal son 'came to himself and arose' — shub as physical and spiritual homecoming.",
      etymology: "From shub (to turn, to return). The most concrete OT repentance word. Not just inner change but turning around and walking the other direction.",
      frequency: 1066,
      testament: 'OT',
    },
  ],
  prayer: [
    {
      greek: 'προσευχή',
      transliteration: 'proseuchē',
      strongs: 'G4335',
      definition: "Prayer, the act of addressing God — the general word for prayer combining proseucho (toward) + euche (vow/wish). Not a magic formula but personal address to a Father. The disciples asked Jesus to teach them proseuchē.",
      etymology: "From pros (toward) + euchomai (to wish, to vow). Prayer is moving toward God, not summoning God toward you.",
      frequency: 37,
      testament: 'NT',
    },
    {
      greek: 'דֵּעָה',
      transliteration: 'tephillah',
      strongs: 'H8605',
      definition: "Prayer, intercession — the primary Hebrew word for prayer. The Psalms are called Tehillim (praises/prayers). The Temple is 'a house of tephillah for all nations' (Isa 56:7).",
      etymology: "From palal (to intercede, to mediate, to judge). Prayer as intercession — standing between God and the situation, mediating.",
      frequency: 77,
      testament: 'OT',
    },
  ],
  power: [
    {
      greek: 'δύναμις',
      transliteration: 'dynamis',
      strongs: 'G1411',
      definition: "Power, might, miraculous ability — the explosive, creative power of God. Root of 'dynamite' and 'dynamic.' The gospel is dynamis of God for salvation; the Spirit gives dynamis for witness.",
      etymology: "From dynamai (to be able, to have power). English: dynamic, dynasty, dynamite. Not coercive authority (exousia) but raw transformative energy.",
      frequency: 119,
      testament: 'NT',
    },
    {
      greek: 'ἐξουσία',
      transliteration: 'exousia',
      strongs: 'G1849',
      definition: "Authority, the right to act — delegated permission or jurisdiction. Distinct from dynamis (raw power). Jesus taught with exousia (Matt 7:29), and gave his disciples exousia over unclean spirits.",
      etymology: "From exesti (it is permitted, it is in one's power). Authority as the right given by a higher power — not just the ability, but the permission.",
      frequency: 102,
      testament: 'NT',
    },
    {
      greek: 'כֹּחַ',
      transliteration: 'koach',
      strongs: 'H3581',
      definition: "Strength, power, ability — physical and divine strength. 'He gives strength (koach) to the weary' (Isa 40:29). The eagle mounting up with wings renews its koach.",
      etymology: "Related to kuwach (to be strong). Used of human physical strength, animal power, and God's creative/redemptive might.",
      frequency: 125,
      testament: 'OT',
    },
  ],
  joy: [
    {
      greek: 'χαρά',
      transliteration: 'chara',
      strongs: 'G5479',
      definition: "Joy — deep, settled delight that is independent of circumstances. The fruit of the Spirit (Gal 5:22). Jesus' joy (John 15:11) — not happiness when things go well, but the bedrock of his relationship with the Father.",
      etymology: "From chairō (to rejoice, to be glad). Related to charis (grace). Joy and grace share a root: joy flows from grace received.",
      frequency: 59,
      testament: 'NT',
    },
    {
      greek: 'שִׂמְחָה',
      transliteration: 'simchah',
      strongs: 'H8057',
      definition: "Joy, gladness, festivity — often expressed bodily and communally. OT joy is loud, celebratory, and public. The Psalms call for shouting, singing, and dancing as expressions of simchah.",
      etymology: "From samach (to rejoice, to be glad). Joy as celebration — the feast, the harvest, the returned exile. Not private sentiment but shared festivity.",
      frequency: 94,
      testament: 'OT',
    },
  ],
  heart: [
    {
      greek: 'καρδία',
      transliteration: 'kardia',
      strongs: 'G2588',
      definition: "Heart — the center of the whole person: thinking, willing, feeling, deciding. Not just emotions (as in modern use) but the seat of intellect and will. 'As a man thinks in his kardia, so is he.'",
      etymology: "The physical heart as the center of life, extended to the whole inner person. The kardia is the address where God writes his law (Heb 8:10).",
      frequency: 156,
      testament: 'NT',
    },
    {
      greek: 'לֵב',
      transliteration: 'lev',
      strongs: 'H3820',
      definition: "Heart, mind, will — the innermost center of human personality. In Hebrew thought, the lev thinks, chooses, and decides — not just feels. 'Love God with all your lev' is an intellectual and volitional command.",
      etymology: "From lev (heart, inner person). Hebrew anthropology is holistic — the lev is not one compartment but the whole self organized around its center.",
      frequency: 598,
      testament: 'OT',
    },
  ],
  lamb: [
    {
      greek: 'ἀμνός',
      transliteration: 'amnos',
      strongs: 'G286',
      definition: "Lamb — specifically used of Jesus as the sacrificial lamb. John the Baptist's cry 'Behold the amnos of God' (John 1:29) connects Jesus to the Passover lamb and Isaiah's suffering servant.",
      etymology: "The standard word for a young sheep used in sacrifice. Amnos appears only 4 times in NT, but each reference is theologically loaded.",
      frequency: 4,
      testament: 'NT',
    },
    {
      greek: 'ἀρνίον',
      transliteration: 'arnion',
      strongs: 'G721',
      definition: "Lamb (diminutive) — used exclusively in Revelation for the risen Christ. 29 times the cosmic ruler of all creation is called 'the arnion.' The Lamb who was slain now reigns. Power through sacrifice.",
      etymology: "Diminutive of arēn (lamb). The choice of this gentle word for the ruler of all creation is one of Revelation's greatest ironies — the slaughtered lamb is the Lion.",
      frequency: 30,
      testament: 'NT',
    },
    {
      greek: 'שֶׂה',
      transliteration: 'seh',
      strongs: 'H7716',
      definition: "Lamb, young sheep or goat — the Passover animal (Exod 12). One seh per household, kept for four days, then slaughtered. Its blood on the doorposts protected Israel — the prototype of Christ's blood.",
      etymology: "The generic term for a sacrificial small animal — lamb or kid. The Passover seh inaugurated Israel's redemption and foreshadowed the ultimate Lamb.",
      frequency: 47,
      testament: 'OT',
    },
  ],
  shepherd: [
    {
      greek: 'ποιμήν',
      transliteration: 'poimēn',
      strongs: 'G4166',
      definition: "Shepherd — both the literal occupation and one of Jesus' key self-descriptions. The 'Good Shepherd' (poimēn kalos) lays down his life for the sheep. Also the metaphor for church leaders (pastors = poimenes).",
      etymology: "From poimainō (to tend, to feed, to shepherd). English 'pastor' comes directly from the Latin translation of poimēn.",
      frequency: 18,
      testament: 'NT',
    },
    {
      greek: 'רֹעֶה',
      transliteration: "ro'eh",
      strongs: 'H7462',
      definition: "Shepherd, herdsman — the dominant OT image for leaders and for God. 'The LORD is my shepherd' (Ps 23). Moses, David, and the prophets were shepherds before leading Israel — the occupation formed the calling.",
      etymology: "From ra'ah (to shepherd, to tend, to feed). The shepherd's duties — feeding, protecting, seeking the lost — become the template for God's care and leaders' responsibilities.",
      frequency: 173,
      testament: 'OT',
    },
  ],
  name: [
    {
      greek: 'ὄνομα',
      transliteration: 'onoma',
      strongs: 'G3686',
      definition: "Name — in biblical thought, far more than a label. The name reveals the nature and character of the person. To pray 'in the name of Jesus' is to pray in his authority and identity. 'The name above every name' (Phil 2:9).",
      etymology: "From gnōskō (to know) — the name is what is known about a person. Knowing someone's name means knowing and having access to their person.",
      frequency: 231,
      testament: 'NT',
    },
    {
      greek: 'שֵׁם',
      transliteration: 'shem',
      strongs: 'H8034',
      definition: "Name, reputation, character — the name carries the full identity and authority of the person. God's shem (YHWH) is not just a title but his self-revelation. 'Hallowed be your shem' means 'let your character be honored.'",
      etymology: "Related to sum (to set, to place). A name is what is placed on a person. God's name was placed on the tabernacle — it was his address.",
      frequency: 864,
      testament: 'OT',
    },
  ],
  blessing: [
    {
      greek: 'εὐλογία',
      transliteration: 'eulogia',
      strongs: 'G2129',
      definition: "Blessing, praise — speaking well of someone; the good word that invokes favor. In NT: both the blessing we receive from God and the blessing/praise we offer to God. The eulogized loaves at the feeding of 5,000.",
      etymology: "From eu (good) + logos (word). Literally: a good word spoken. English 'eulogy' comes directly from this root — a good word spoken at death.",
      frequency: 16,
      testament: 'NT',
    },
    {
      greek: 'בְּרָכָה',
      transliteration: 'berakah',
      strongs: 'H1293',
      definition: "Blessing — the life-giving power spoken over a person or passed from one generation to the next. The Patriarchal blessings (Abraham, Isaac, Jacob) were binding declarations of destiny. God's berakah makes fruitful.",
      etymology: "From barak (to bless, to kneel). Related to berek (knee) — blessing was given on the knee, receiving it was kneeling. Blessing involves homage and gift.",
      frequency: 71,
      testament: 'OT',
    },
  ],
  creation: [
    {
      greek: 'κτίσις',
      transliteration: 'ktisis',
      strongs: 'G2937',
      definition: "Creation, creature — the whole created order. Paul's 'the whole ktisis groans' (Rom 8:22) means the entire cosmos awaits redemption, not just humans. The gospel's scope is cosmic: a new ktisis.",
      etymology: "From ktizō (to create, to found). The creation is not a backdrop for the human story — it has its own destiny and participates in redemption.",
      frequency: 19,
      testament: 'NT',
    },
    {
      greek: 'בָּרָא',
      transliteration: 'bara',
      strongs: 'H1254',
      definition: "To create — exclusively used of God's creative act. Humans make (asah) and form (yatsar), but only God bara. Genesis 1 uses all three words — bara signals the uniquely divine act of bringing something from nothing.",
      etymology: "Bara is never used with a human subject in the OT. It always describes God's activity. The creation is not an accident or conflict but the sovereign word-act of the one God.",
      frequency: 54,
      testament: 'OT',
    },
  ],
  eternal: [
    {
      greek: 'αἰώνιος',
      transliteration: 'aiōnios',
      strongs: 'G166',
      definition: "Eternal, age-long — belonging to the age to come. 'Eternal life' (zōē aiōnios) in John is not just endless duration but a quality of life: knowing God (John 17:3). It begins now, at belief, not only after death.",
      etymology: "From aiōn (age, era). Not just 'a long time' but 'belonging to God's age' — the quality of the age to come breaking into the present.",
      frequency: 71,
      testament: 'NT',
    },
    {
      greek: 'עוֹלָם',
      transliteration: 'olam',
      strongs: 'H5769',
      definition: "Forever, eternity, antiquity — 'from olam to olam' means from everlasting to everlasting. Both backwards (from ancient times) and forwards (to endless time). God's covenant love (hesed) endures le-olam va-ed — forever and ever.",
      etymology: "From alam (to be hidden, to be concealed). The horizon that cannot be seen — time stretching beyond sight in both directions.",
      frequency: 439,
      testament: 'OT',
    },
  ],
  servant: [
    {
      greek: 'δοῦλος',
      transliteration: 'doulos',
      strongs: 'G1401',
      definition: "Slave, servant — not merely an employee but one whose will is completely surrendered to another. Paul calls himself a doulos of Christ. Modern translations often soften 'slave' to 'servant,' losing the radical claim of total belonging.",
      etymology: "From deō (to bind). A doulos is bound — their identity, time, and work belong entirely to the master. The deepest devotion in the NT is called slavery.",
      frequency: 124,
      testament: 'NT',
    },
    {
      greek: 'עֶבֶד',
      transliteration: 'eved',
      strongs: 'H5650',
      definition: "Servant, slave, worshipper — the Servant Songs of Isaiah (42, 49, 50, 53) describe the eved Yahweh, the Servant of the LORD who suffers vicariously. Moses, David, and the prophets are called eved — it is a title of honor.",
      etymology: "From avad (to work, to serve, to worship). The same word means 'work,' 'serve,' and 'worship' — in Hebrew thought, these are the same activity.",
      frequency: 800,
      testament: 'OT',
    },
  ],
  wrath: [
    {
      greek: 'ὀργή',
      transliteration: 'orgē',
      strongs: 'G3709',
      definition: "Wrath, anger — God's settled, righteous opposition to sin and evil. Not petulant rage but the necessary response of a holy God to wickedness. Paul's 'wrath of God is revealed' (Rom 1:18) is present-tense, active, ongoing.",
      etymology: "From orgaō (to swell, to be ripe). Not impulsive anger but the built-up pressure of holy justice. God's wrath is not a mood but his consistent character toward unrepentant evil.",
      frequency: 36,
      testament: 'NT',
    },
    {
      greek: 'אַף',
      transliteration: 'aph',
      strongs: 'H639',
      definition: "Anger, nostril — originally the flared nostril of hot breath, extended to anger. God's anger (aph) in the OT is always in response to injustice or covenant-breaking. It is never capricious.",
      etymology: "From aneph (to breathe hard). The physical sensation of anger — hot breath through flared nostrils — became the word for anger itself.",
      frequency: 276,
      testament: 'OT',
    },
  ],
  blood: [
    {
      greek: 'αἷμα',
      transliteration: 'haima',
      strongs: 'G129',
      definition: "Blood — the physical carrier of life (Lev 17:11). In NT: Christ's haima as the means of atonement, new covenant ratification, and cleansing. 'The blood of Jesus cleanses us from all sin' (1 John 1:7).",
      etymology: "The physical blood, extended to the life it represents. In atonement theology, the blood is offered because life is in the blood — it is life given for life.",
      frequency: 97,
      testament: 'NT',
    },
    {
      greek: 'דָּם',
      transliteration: 'dam',
      strongs: 'H1818',
      definition: "Blood, life — 'the life of the flesh is in the blood' (Lev 17:11). Blood is life itself. Shed blood cries out — Abel's dam cried to God from the ground. The sacrificial blood covered sin by representing surrendered life.",
      etymology: "Related to adamah (ground) and adam (humankind). Blood and earth share a root — humanity is earthly, mortal, alive only while the blood flows.",
      frequency: 360,
      testament: 'OT',
    },
  ],
}

export const KEY_PASSAGES = {
  love: [
    {
      reference: 'John 21:15–17',
      english: '"Simon son of John, do you love [agapas] me more than these?" … "Yes, Lord, you know that I love [philō] you."',
      greek: 'Σίμων Ἰωάννου, ἀγαπᾷς με πλέον τούτων; … Ναί, Κύριε, σὺ οἶδας ὅτι φιλῶ σε.',
      note: 'Jesus uses agapē (covenant love); Peter responds with phileō (affection). Jesus tests whether Peter will commit to sacrificial love, not just sentiment.',
    },
    {
      reference: '1 Corinthians 13:13',
      english: '"And now these three remain: faith, hope and love [agapē]. But the greatest of these is love."',
      greek: 'νυνὶ δὲ μένει πίστις, ἐλπίς, ἀγάπη, τὰ τρία ταῦτα· μείζων δὲ τούτων ἡ ἀγάπη.',
      note: "Paul's great triad — agapē surpasses even faith and hope because it endures into eternity.",
    },
    {
      reference: 'John 3:16',
      english: '"For God so loved [ēgapēsen] the world that he gave his one and only Son…"',
      greek: 'Οὕτως γὰρ ἠγάπησεν ὁ Θεὸς τὸν κόσμον, ὥστε τὸν Υἱὸν αὐτοῦ τὸν μονογενῆ ἔδωκεν',
      note: "God's love (agapē) for the cosmos — not sentimental affection but the costly act of giving.",
    },
    {
      reference: 'Deuteronomy 6:5',
      english: '"Love [ahavah] the LORD your God with all your heart and with all your soul and with all your strength."',
      greek: 'וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל-לְבָבְךָ וּבְכָל-נַפְשְׁךָ וּבְכָל-מְאֹדֶךָ',
      note: "The Shema — the foundational command Jesus calls the greatest. Total love: cognitive (heart/lev), volitional (soul/nephesh), and material (strength/me'od).",
    },
  ],
  faith: [
    {
      reference: 'Hebrews 11:1',
      english: '"Now faith [pistis] is the substance of things hoped for, the evidence of things not seen."',
      greek: 'Ἔστιν δὲ πίστις ἐλπιζομένων ὑπόστασις, πραγμάτων ἔλεγχος οὐ βλεπομένων.',
      note: "The NT's most precise definition of pistis: hypostasis (substance/foundation) and elenchos (evidence/conviction).",
    },
    {
      reference: 'Romans 1:17',
      english: '"The righteous shall live by faith [pistis]." (Quoting Hab 2:4 — emunah)',
      greek: 'ὁ δὲ δίκαιος ἐκ πίστεως ζήσεται.',
      note: 'Paul quotes the Hebrew emunah (faithfulness) and renders it pistis — bridging OT covenant faithfulness and NT justifying faith.',
    },
    {
      reference: 'Galatians 2:20',
      english: '"The life I now live in the body, I live by faith [pistei] in the Son of God, who loved me and gave himself for me."',
      greek: 'ζῶ δὲ οὐκέτι ἐγώ, ζῇ δὲ ἐν ἐμοὶ Χριστός· ὃ δὲ νῦν ζῶ ἐν σαρκί, ἐν πίστει ζῶ τῇ τοῦ υἱοῦ τοῦ Θεοῦ',
      note: "Paul's most personal statement of faith: not a doctrine he holds, but a person he trusts — 'who loved me and gave himself for me.'",
    },
  ],
  grace: [
    {
      reference: 'Ephesians 2:8–9',
      english: '"For it is by grace [chariti] you have been saved, through faith — and this is not from yourselves, it is the gift of God."',
      greek: 'Τῇ γὰρ χάριτί ἐστε σεσῳσμένοι διὰ πίστεως· καὶ τοῦτο οὐκ ἐξ ὑμῶν, Θεοῦ τὸ δῶρον',
      note: "The grammatical anchor of Reformation theology. Charis is God's initiative; pistis is the human response.",
    },
    {
      reference: 'John 1:14',
      english: '"The Word became flesh… full of grace [charitos] and truth."',
      greek: 'ὁ Λόγος σὰρξ ἐγένετο… πλήρης χάριτος καὶ ἀληθείας.',
      note: 'John pairs charis (grace) with alētheia (truth) — the character of the incarnate Logos.',
    },
    {
      reference: '2 Corinthians 12:9',
      english: '"My grace [charis] is sufficient for you, for my power is made perfect in weakness."',
      greek: 'ἀρκεῖ σοι ἡ χάρις μου· ἡ γὰρ δύναμις ἐν ἀσθενείᾳ τελεῖται.',
      note: "The paradox of grace: God's charis is not distributed when we are strong, but perfected through our weakness.",
    },
  ],
  peace: [
    {
      reference: 'Philippians 4:7',
      english: '"And the peace [eirēnē] of God, which surpasses all understanding, will guard your hearts and minds in Christ Jesus."',
      greek: 'ἡ εἰρήνη τοῦ Θεοῦ ἡ ὑπερέχουσα πάντα νοῦν φρουρήσει τὰς καρδίας ὑμῶν',
      note: 'Eirēnē as military metaphor: peace "guards" (phrourēsei — a garrison) your inner life.',
    },
    {
      reference: 'Numbers 6:24–26',
      english: '"The LORD bless you and keep you… and give you shalom."',
      greek: 'יְבָרֶכְךָ יְהוָה וְיִשְׁמְרֶךָ… וְיָשֵׂם לְךָ שָׁלוֹם.',
      note: 'The Aaronic blessing — shalom is the culminating gift. More than tranquility: comprehensive flourishing.',
    },
    {
      reference: 'John 14:27',
      english: '"Peace [eirēnē] I leave with you; my peace I give you. Not as the world gives do I give to you."',
      greek: 'εἰρήνην ἀφίημι ὑμῖν, εἰρήνην τὴν ἐμὴν δίδωμι ὑμῖν· οὐ καθὼς ὁ κόσμος δίδωσιν ἐγὼ δίδωμι ὑμῖν.',
      note: "The world's eirēnē = absence of conflict. Christ's eirēnē = presence of God. Two entirely different things sharing one word.",
    },
  ],
  spirit: [
    {
      reference: 'Genesis 1:2',
      english: '"The Spirit [ruach] of God was hovering over the waters."',
      greek: 'וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל-פְּנֵי הַמָּיִם',
      note: "First appearance of ruach in Scripture. The Spirit's hovering (merachefet) mirrors a mother bird over her nest — creative, nurturing presence.",
    },
    {
      reference: 'John 3:8',
      english: '"The wind [pneuma] blows wherever it pleases… So it is with everyone born of the Spirit [pneumatos]."',
      greek: 'τὸ πνεῦμα ὅπου θέλει πνεῖ… οὕτως ἐστὶν πᾶς ὁ γεγεννημένος ἐκ τοῦ πνεύματος.',
      note: 'Jesus plays on pneuma meaning both "wind" and "Spirit" — the invisibility and power of the Spirit mirrors the wind.',
    },
    {
      reference: 'Ezekiel 37:9–10',
      english: '"Come, breath [ruach], from the four winds… breathe into these slain, that they may live."',
      greek: 'בֹּאִי מֵהָרוּחַ מֵאַרְבַּע רוּחוֹת… וְחָיוּ',
      note: 'Ezekiel commands the ruach to animate dry bones — the Spirit as the resurrection power of God. The valley-of-bones vision unites all three meanings: wind, breath, Spirit.',
    },
  ],
  hope: [
    {
      reference: 'Hebrews 6:19',
      english: '"We have this hope as an anchor for the soul, firm and secure."',
      greek: 'ἣν ὡς ἄγκυραν ἔχομεν τῆς ψυχῆς, ἀσφαλῆ τε καὶ βεβαίαν',
      note: 'The anchor (agkyra) was a common symbol of hope in ancient Mediterranean culture. The writer redefines it: hope anchored not to the sea floor but to heaven itself.',
    },
    {
      reference: 'Romans 8:24–25',
      english: '"For in this hope we were saved. But hope that is seen is no hope at all… we hope for what we do not yet have."',
      greek: 'τῇ γὰρ ἐλπίδι ἐσώθημεν· ἐλπὶς δὲ βλεπομένη οὐκ ἔστιν ἐλπίς',
      note: 'Paul defines elpis by what it is NOT — visible, possessed. True hope is confident in the unseen.',
    },
    {
      reference: 'Lamentations 3:21–23',
      english: '"Yet this I call to mind and therefore I have hope [tiqvah]… great is your faithfulness."',
      greek: 'זֹאת אָשִׁיב אֶל-לִבִּי עַל-כֵּן אוֹחִיל',
      note: "Written amid Jerusalem's destruction — hope is not optimism but the act of calling something to mind. Tiqvah in the ruins.",
    },
  ],
  light: [
    {
      reference: 'John 1:4–5',
      english: '"In him was life, and that life was the light [phōs] of all mankind. The light shines in the darkness, and the darkness has not overcome it."',
      greek: 'ἐν αὐτῷ ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων· καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει',
      note: 'Katalambanō (overcome/seize) — the darkness cannot "comprehend" OR "overpower" the light. Both meanings are likely intentional.',
    },
    {
      reference: 'Genesis 1:3',
      english: '"And God said, Let there be light [or]; and there was light."',
      greek: 'וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי-אוֹר',
      note: "God's first act of creation is verbal — and it is light. John 1 deliberately echoes this: the Logos who IS light.",
    },
    {
      reference: 'Matthew 5:14–16',
      english: '"You are the light [phōs] of the world. A city on a hill cannot be hidden."',
      greek: 'Ὑμεῖς ἐστε τὸ φῶς τοῦ κόσμου.',
      note: "Jesus calls himself the phōs of the world (John 8:12) and then calls his disciples the same thing (Matt 5:14). The church participates in Christ's own identity.",
    },
  ],
  truth: [
    {
      reference: 'John 14:6',
      english: '"Jesus said, I am the way, the truth [alētheia], and the life."',
      greek: 'λέγει αὐτῷ ὁ Ἰησοῦς· Ἐγώ εἰμι ἡ ὁδὸς καὶ ἡ ἀλήθεια καὶ ἡ ζωή',
      note: 'Jesus identifies himself AS truth — not merely as a teacher of truth. Alētheia (un-hiddenness) applied to a person: the one in whom reality is disclosed.',
    },
    {
      reference: 'John 18:38',
      english: '"What is truth?" Pilate asked. He went back outside.',
      greek: 'λέγει αὐτῷ ὁ Πιλᾶτος· Τί ἐστιν ἀλήθεια;',
      note: "The irony of John's Gospel: Pilate asks the question about alētheia while standing in front of the one who IS alētheia.",
    },
    {
      reference: 'Psalm 51:6',
      english: '"Yet you desired truth [emet] in the inward parts; you taught me wisdom in that secret place."',
      greek: 'הֵן-אֱמֶת חָפַצְתָּ בַטֻּחוֹת',
      note: "David's confession — God desires emet (reliable truth) in the hidden interior, not just external religious compliance. Truth is an inward reality.",
    },
  ],
  gospel: [
    {
      reference: 'Romans 1:16',
      english: '"For I am not ashamed of the gospel [euangelion], because it is the power of God that brings salvation."',
      greek: 'Οὐ γὰρ ἐπαισχύνομαι τὸ εὐαγγέλιον· δύναμις γὰρ Θεοῦ ἐστιν εἰς σωτηρίαν',
      note: "The gospel is dynamis (power) — the same word used for miracles. Paul's mission statement for the letter to Rome.",
    },
    {
      reference: 'Mark 1:14–15',
      english: '"Jesus went into Galilee, proclaiming the good news [euangelion] of God."',
      greek: 'ἦλθεν ὁ Ἰησοῦς εἰς τὴν Γαλιλαίαν κηρύσσων τὸ εὐαγγέλιον τοῦ Θεοῦ',
      note: "Mark's first use — euangelion precedes Paul. Jesus himself announces the 'gospel of God' before Paul theologizes it.",
    },
    {
      reference: 'Isaiah 52:7',
      english: '"How beautiful are the feet of those who bring good news [mevaser]!"',
      greek: 'מַה-נָּאווּ עַל-הֶהָרִים רַגְלֵי מְבַשֵּׂר',
      note: "Paul quotes this verse in Romans 10:15. The OT mevaser (herald of good news) is the prototype of NT euangelion. The gospel is not a NT invention — it was announced to Abraham (Gal 3:8).",
    },
  ],
  word: [
    {
      reference: 'John 1:1',
      english: '"In the beginning was the Word [Logos], and the Word was with God, and the Word was God."',
      greek: 'Ἐν ἀρχῇ ἦν ὁ Λόγος, καὶ ὁ Λόγος ἦν πρὸς τὸν Θεόν, καὶ Θεὸς ἦν ὁ Λόγος.',
      note: 'John opens his Gospel matching Genesis 1:1 (En archē = Bereshit). The Logos is eternal, relational (pros = toward/face-to-face), and divine.',
    },
    {
      reference: 'Hebrews 4:12',
      english: '"For the word [logos] of God is alive and active, sharper than any double-edged sword."',
      greek: 'Ζῶν γὰρ ὁ λόγος τοῦ Θεοῦ καὶ ἐνεργής, καὶ τομώτερος ὑπὲρ πᾶσαν μάχαιραν δίστομον',
      note: 'The logos is zōn (living) and energēs (energetic/active) — not a static text but a living agency.',
    },
    {
      reference: 'Isaiah 55:11',
      english: '"So is my word [dabar] that goes out from my mouth: it will not return to me empty."',
      greek: 'כֵּן יִהְיֶה דְבָרִי אֲשֶׁר יֵצֵא מִפִּי לֹא-יָשׁוּב אֵלַי רֵיקָם',
      note: "God's dabar is an agent, not a sound. It goes forth, accomplishes, and returns with a report. The prophetic word is performative.",
    },
  ],
  salvation: [
    {
      reference: 'Luke 19:9–10',
      english: '"Today salvation [sōtēria] has come to this house… For the Son of Man came to seek and to save the lost."',
      greek: 'σήμερον σωτηρία τῷ οἴκῳ τούτῳ ἐγένετο… ἦλθεν γὰρ ὁ υἱὸς τοῦ ἀνθρώπου ζητῆσαι καὶ σῶσαι τὸ ἀπολωλός.',
      note: "Zacchaeus receives sōtēria before the cross — salvation is the presence of the Savior, not just future security. 'Today' is always the tense of salvation.",
    },
    {
      reference: 'Psalm 27:1',
      english: '"The LORD is my light and my salvation [yeshuah]; whom shall I fear?"',
      greek: 'יְהוָה אוֹרִי וְיִשְׁעִי מִמִּי אִירָא',
      note: "David's yeshuah (salvation) is identical to Jesus' name. The Psalm is implicitly Messianic: 'The LORD is my Jesus' — the Savior is the salvation.",
    },
    {
      reference: 'Philippians 2:12',
      english: '"Work out your salvation [sōtērian] with fear and trembling."',
      greek: 'τὴν ἑαυτῶν σωτηρίαν κατεργάζεσθε μετὰ φόβου καὶ τρόμου',
      note: "'Work out' (katergazomai) means to bring to completion — like working a field. The salvation already received must be expressed into the whole of life.",
    },
  ],
  redemption: [
    {
      reference: 'Romans 3:24',
      english: '"All are justified freely by his grace through the redemption [apolytrōseōs] that came by Christ Jesus."',
      greek: 'δικαιούμενοι δωρεὰν τῇ αὐτοῦ χάριτι διὰ τῆς ἀπολυτρώσεως τῆς ἐν Χριστῷ Ἰησοῦ',
      note: "Apolytrōsis, charis, and dikaiōsynē appear in one sentence: the marketplace (redemption), the throne (grace), and the courtroom (justification) all describe one act.",
    },
    {
      reference: 'Ruth 4:4–6',
      english: '"I will redeem [ga\'al] it," Boaz said. "I will redeem it."',
      greek: 'אָנֹכִי אֶגְאָל',
      note: "Boaz as go'el kinsman-redeemer is one of the OT's clearest pictures of Christ: near of kin, willing and able to redeem, paying the full price to restore what was lost.",
    },
    {
      reference: 'Isaiah 43:1',
      english: '"Do not fear, for I have redeemed [ga\'alticha] you; I have called you by name, you are mine."',
      greek: 'אַל-תִּירָא כִּי גְאַלְתִּיךָ קָרָאתִי בְשִׁמְךָ לִי-אָתָּה',
      note: "The ga'al and the shem in one verse: God the kinsman-redeemer calls Israel by name, claiming them. Redemption is personal, not transactional.",
    },
  ],
  righteousness: [
    {
      reference: 'Romans 3:21–22',
      english: '"But now apart from the law the righteousness [dikaiosynē] of God has been made known… righteousness of God through faith in Jesus Christ."',
      greek: 'νυνὶ δὲ χωρὶς νόμου δικαιοσύνη Θεοῦ πεφανέρωται… δικαιοσύνη δὲ Θεοῦ διὰ πίστεως Ἰησοῦ Χριστοῦ',
      note: "The 'righteousness of God' is both his own character and the status he confers. Paul insists it comes through pistis (faith), not nomos (law).",
    },
    {
      reference: '2 Corinthians 5:21',
      english: '"God made him who had no sin to be sin for us, so that in him we might become the righteousness [dikaiosynē] of God."',
      greek: 'τὸν μὴ γνόντα ἁμαρτίαν ὑπὲρ ἡμῶν ἁμαρτίαν ἐποίησεν, ἵνα ἡμεῖς γενώμεθα δικαιοσύνη Θεοῦ ἐν αὐτῷ.',
      note: "The great exchange: our sin imputed to Christ, his dikaiosynē imputed to us. We don't just receive forgiveness — we become God's righteousness.",
    },
    {
      reference: 'Amos 5:24',
      english: '"But let justice roll on like a river, righteousness [tsedaqah] like a never-failing stream."',
      greek: 'וְיִגַּל כַּמַּיִם מִשְׁפָּט וּצְדָקָה כְּנַחַל אֵיתָן',
      note: "MLK quoted this in the 'I Have a Dream' speech. Tsedaqah as social righteousness: inseparable from justice. The prophetic tradition will not let tsedaqah be only personal and spiritual.",
    },
  ],
  mercy: [
    {
      reference: 'Luke 18:13',
      english: '"God, have mercy [hilasthēti] on me, a sinner."',
      greek: 'ὁ Θεός, ἱλάσθητί μοι τῷ ἁμαρτωλῷ.',
      note: "The tax collector's prayer uses hilaskomai — to propitiate, to make atonement. He doesn't claim goodness; he claims only that God can be merciful.",
    },
    {
      reference: 'Micah 6:8',
      english: '"What does the LORD require of you? To act justly, to love mercy [hesed], and to walk humbly with your God."',
      greek: 'מָה-יְהוָה דֹּרֵשׁ מִמְּךָ כִּי אִם-עֲשׂוֹת מִשְׁפָּט וְאַהֲבַת חֶסֶד וְהַצְנֵעַ לֶכֶת עִם-אֱלֹהֶיךָ',
      note: "The three requirements: mishpat (justice), hesed (covenant mercy), and humility. They cannot be separated — mercy without justice is sentimentality; justice without mercy is cruelty.",
    },
    {
      reference: 'Hosea 2:19',
      english: '"I will betroth you to me forever… in lovingkindness [hesed] and mercy [rachamim]."',
      greek: 'וְאֵרַשְׂתִּיךְ לִי לְעוֹלָם… בְּחֶסֶד וּבְרַחֲמִים',
      note: "God's mercy as marriage covenant: both hesed (faithfulness) and rachamim (womb-love) describe his commitment. The covenant is both legal and visceral.",
    },
  ],
  covenant: [
    {
      reference: 'Genesis 15:17–18',
      english: '"A smoking firepot with a blazing torch appeared and passed between the pieces. On that day the LORD made [cut] a covenant [berit] with Abram."',
      greek: 'וְהִנֵּה תַנּוּר עָשָׁן וְלַפִּיד אֵשׁ אֲשֶׁר עָבַר בֵּין הַגְּזָרִים הָאֵלֶּה׃ בַּיּוֹם הַהוּא כָּרַת יְהוָה אֶת-אַבְרָם בְּרִית',
      note: "Normally both parties walk between the cut pieces. Here only God (as fire) passes through — he takes the oath alone. If this covenant breaks, God himself bears the consequences.",
    },
    {
      reference: 'Luke 22:20',
      english: '"This cup is the new covenant [diathēkē] in my blood, which is poured out for you."',
      greek: 'τοῦτο τὸ ποτήριον ἡ καινὴ διαθήκη ἐν τῷ αἵματί μου τὸ ὑπὲρ ὑμῶν ἐκχυνόμενον.',
      note: "Jesus ratifies the new covenant (Jer 31:31) with his own blood — fulfilling the animal sacrifices by becoming the covenant sacrifice himself.",
    },
    {
      reference: 'Jeremiah 31:31–33',
      english: '"I will make a new covenant [berit]… I will put my law in their minds and write it on their hearts."',
      greek: 'הִנֵּה יָמִים בָּאִים… וְכָרַתִּי אֶת-בֵּית יִשְׂרָאֵל בְּרִית חֲדָשָׁה',
      note: "The new berit (Jer 31) is the OT's most explicit covenant promise. The difference from Sinai: internalized law, universal knowledge, complete forgiveness. Jesus claims to fulfill this.",
    },
  ],
  forgiveness: [
    {
      reference: 'Luke 7:47–48',
      english: '"Therefore I tell you, her many sins have been forgiven [aphentai] — as her great love has shown."',
      greek: 'οὗ χάριν λέγω σοι, ἀφέωνται αἱ ἁμαρτίαι αὐτῆς αἱ πολλαί',
      note: "Jesus' declaration of aphesis is shocking — only God forgives sins (Mark 2:7). His authority to declare forgiveness is an implicit claim to divinity.",
    },
    {
      reference: 'Colossians 2:13–14',
      english: '"Having forgiven [charisomenos] us all our sins, having canceled the charge of our legal indebtedness, which stood against us."',
      greek: 'χαρισάμενος ἡμῖν πάντα τὰ παραπτώματα, ἐξαλείψας τὸ καθ᾽ ἡμῶν χειρόγραφον',
      note: "The 'certificate of debt' (cheirographon) nailed to the cross — a commercial term for an IOU. Every accusation against us was nailed to the cross with Christ.",
    },
    {
      reference: 'Psalm 130:3–4',
      english: '"If you, LORD, kept a record of sins, Lord, who could stand? But with you there is forgiveness [selichah], so that we may fear you."',
      greek: 'אִם-עֲוֺנוֹת תִּשְׁמָר-יָהּ אֲדֹנָי מִי יַעֲמֹד׃ כִּי-עִמְּךָ הַסְּלִיחָה לְמַעַן תִּוָּרֵא',
      note: "Paradox: selichah produces fear (reverence) rather than presumption. Knowing God forgives increases awe, not carelessness.",
    },
  ],
  glory: [
    {
      reference: 'Exodus 33:18–19',
      english: '"Show me your glory [kabod]." … "I will cause all my goodness to pass in front of you."',
      greek: 'הַרְאֵנִי נָא אֶת-כְּבֹדֶךָ… אֲנִי אַעֲבִיר כָּל-טוּבִי עַל-פָּנֶיךָ',
      note: "Moses asks to see kabod; God answers by revealing his character (Exod 34:6-7). The glory OF God is the goodness OF God — the character of one who is merciful, gracious, and faithful.",
    },
    {
      reference: 'John 17:22',
      english: '"The glory [doxa] you gave me I have given to them, that they may be one as we are one."',
      greek: 'κἀγὼ τὴν δόξαν ἣν δέδωκάς μοι δέδωκα αὐτοῖς, ἵνα ὦσιν ἓν καθὼς ἡμεῖς ἕν',
      note: "Jesus shares his doxa with his disciples — the same glory the Father gave him. The glory of the Trinity becomes the shared life of the church.",
    },
    {
      reference: 'Isaiah 6:3',
      english: '"Holy, holy, holy is the LORD Almighty; the whole earth is full of his glory [kabod]."',
      greek: 'קָדוֹשׁ קָדוֹשׁ קָדוֹשׁ יְהוָה צְבָאוֹת מְלֹא כָל-הָאָרֶץ כְּבוֹדוֹ',
      note: "The Trisagion — the triple 'holy' is the highest Hebrew superlative. The kabod fills the earth; the whole created order is saturated with God's glory, visible to those with eyes to see.",
    },
  ],
  kingdom: [
    {
      reference: 'Mark 1:15',
      english: '"The time has come. The kingdom [basileia] of God has come near. Repent and believe the good news!"',
      greek: 'πεπλήρωται ὁ καιρὸς καὶ ἤγγικεν ἡ βασιλεία τοῦ Θεοῦ· μετανοεῖτε καὶ πιστεύετε ἐν τῷ εὐαγγελίῳ.',
      note: "Jesus' opening proclamation. Kairos (appointed time) + basileia (kingdom) + metanoia (repentance) + euangelion (gospel): four loaded words in one sentence.",
    },
    {
      reference: 'Daniel 7:14',
      english: '"He was given authority, glory and sovereign power [malkuth]; all nations and peoples of every language worshiped him."',
      greek: 'וְלֵהּ יְהִיב שָׁלְטָן וִיקָר וּמַלְכוּ',
      note: "Daniel's Son of Man receives malkuth (kingdom/dominion) from the Ancient of Days. Jesus quotes this scene at his trial (Mark 14:62) — claiming to be this figure.",
    },
    {
      reference: 'Matthew 6:10',
      english: '"Your kingdom [basileia] come, your will be done, on earth as it is in heaven."',
      greek: 'ἐλθέτω ἡ βασιλεία σου· γενηθήτω τὸ θέλημά σου, ὡς ἐν οὐρανῷ καὶ ἐπὶ γῆς.',
      note: "The Lord's Prayer defines the basileia: it is wherever God's will is done. Heaven is where his will is done fully — the prayer asks earth to become like that.",
    },
  ],
  sin: [
    {
      reference: 'Romans 5:12',
      english: '"Therefore, just as sin [hamartia] entered the world through one man, and death through sin…"',
      greek: 'διὰ τοῦτο ὥσπερ δι᾽ ἑνὸς ἀνθρώπου ἡ ἁμαρτία εἰς τὸν κόσμον εἰσῆλθεν',
      note: "Hamartia entered the world as a power — not just bad acts. Paul personifies sin as a ruling force that entered through Adam and now enslaves humanity.",
    },
    {
      reference: 'Psalm 51:1–4',
      english: '"Have mercy on me, O God… Against you, you only, have I sinned [chatati]."',
      greek: 'חָנֵּנִי אֱלֹהִים כְּחַסְדֶּךָ… לְךָ לְבַדְּךָ חָטָאתִי',
      note: "David's prayer after adultery and murder. 'Against you only' is not denial of human harm but recognition of the deepest dimension of sin: all sin is ultimately against God.",
    },
    {
      reference: '1 John 1:8–9',
      english: '"If we claim to be without sin [hamartian], we deceive ourselves… If we confess our sins, he is faithful and just to forgive."',
      greek: 'ἐὰν εἴπωμεν ὅτι ἁμαρτίαν οὐκ ἔχομεν, ἑαυτοὺς πλανῶμεν',
      note: "The condition is not sinlessness but honesty. Denial of hamartia is self-deception; confession activates God's faithfulness and justice.",
    },
  ],
  resurrection: [
    {
      reference: '1 Corinthians 15:20–22',
      english: '"But Christ has indeed been raised from the dead, the firstfruits [aparchē] of those who have fallen asleep."',
      greek: 'νυνὶ δὲ Χριστὸς ἐγήγερται ἐκ νεκρῶν, ἀπαρχὴ τῶν κεκοιμημένων.',
      note: "Aparchē (firstfruits) is an OT agricultural term: the first sheaf guarantees the full harvest. Christ's anastasis is not isolated but the guarantee of all believers' future resurrection.",
    },
    {
      reference: 'John 11:25–26',
      english: '"I am the resurrection [anastasis] and the life. Whoever believes in me will live, even though they die."',
      greek: 'ἐγώ εἰμι ἡ ἀνάστασις καὶ ἡ ζωή· ὁ πιστεύων εἰς ἐμέ, κἂν ἀποθάνῃ, ζήσεται',
      note: "Jesus doesn't say 'I will provide resurrection' but 'I AM the anastasis.' He is not the agent of life — he is the life. Martha expected future resurrection; Jesus offers present participation.",
    },
    {
      reference: 'Ezekiel 37:12–14',
      english: '"I will open your graves and bring you up from them… and I will put my Spirit in you and you will live."',
      greek: 'פֹּתֵחַ אֶת-קִבְרוֹתֵיכֶם… וְנָתַתִּי רוּחִי בָכֶם וִחְיִיתֶם',
      note: "Ezekiel's dry bones vision is collective resurrection — Israel restored as a nation. But the NT draws on it for individual resurrection: the ruach that revived Israel is the same Spirit who raised Christ.",
    },
  ],
  wisdom: [
    {
      reference: '1 Corinthians 1:22–24',
      english: '"Jews demand signs and Greeks look for wisdom [sophian], but we preach Christ crucified… Christ the power and the wisdom [sophia] of God."',
      greek: 'Ἰουδαῖοι σημεῖα αἰτοῦσιν καὶ Ἕλληνες σοφίαν ζητοῦσιν· ἡμεῖς δὲ κηρύσσομεν Χριστὸν ἐσταυρωμένον',
      note: "Paul's inversion: the cross, which looks like foolishness (mōria), IS the sophia of God. The crucified Christ subverts all human wisdom systems.",
    },
    {
      reference: 'Proverbs 8:22–23',
      english: '"The LORD brought me [Wisdom/chokmah] forth as the first of his works… I was appointed from eternity."',
      greek: 'יְהוָה קָנָנִי רֵאשִׁית דַּרְכּוֹ קֶדֶם מִפְעָלָיו מֵאָז',
      note: "Chokmah personified as present at creation — a proto-Christological passage. John 1 ('In the beginning was the Logos') echoes this directly.",
    },
    {
      reference: 'James 1:5',
      english: '"If any of you lacks wisdom [sophia], let him ask God, who gives generously to all without finding fault."',
      greek: 'Εἴ τις δὲ ὑμῶν λείπεται σοφίας, αἰτείτω παρὰ τοῦ διδόντος Θεοῦ πᾶσιν ἁπλῶς',
      note: "Sophia is not reserved for the intellectually gifted — it is given by God to those who ask. The condition is asking, not qualifying.",
    },
  ],
  holy: [
    {
      reference: 'Isaiah 6:1–3',
      english: '"Holy, holy, holy [qadosh, qadosh, qadosh] is the LORD Almighty; the whole earth is full of his glory."',
      greek: 'קָדוֹשׁ קָדוֹשׁ קָדוֹשׁ יְהוָה צְבָאוֹת',
      note: "The seraphim's cry — the only attribute of God stated in triplicate in Scripture. Holiness is the sum of all God's attributes: what he is, utterly and completely.",
    },
    {
      reference: '1 Peter 1:15–16',
      english: '"Just as he who called you is holy [hagios], so be holy in all you do; for it is written: Be holy, because I am holy."',
      greek: 'ἀλλὰ κατὰ τὸν καλέσαντα ὑμᾶς ἅγιον καὶ αὐτοὶ ἅγιοι ἐν πάσῃ ἀναστροφῇ γενήθητε',
      note: "Peter quotes Leviticus (11:44) in a letter to Gentile Christians. The call to holiness is not a ladder to climb but a family resemblance to grow into.",
    },
    {
      reference: 'Leviticus 19:2',
      english: '"Speak to the entire assembly of Israel and say to them: Be holy [qadoshim] because I, the LORD your God, am holy."',
      greek: 'דַּבֵּר אֶל-כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם קְדֹשִׁים תִּהְיוּ',
      note: "The Holiness Code — God's character as the ground and standard for human ethics. Not 'be holy to gain my favor' but 'be holy because you already belong to the Holy One.'",
    },
  ],
  repentance: [
    {
      reference: 'Acts 2:38',
      english: '"Repent [metanoēsate] and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins."',
      greek: 'Μετανοήσατε, καὶ βαπτισθήτω ἕκαστος ὑμῶν ἐπὶ τῷ ὀνόματι Ἰησοῦ Χριστοῦ',
      note: "Peter's response to 'What shall we do?' — metanoia is the first step. Not emotion but action: a change that is visible in baptism.",
    },
    {
      reference: 'Luke 15:17–18',
      english: '"He came to himself… I will set out and go back [shub] to my father."',
      greek: 'εἰς ἑαυτὸν δὲ ἐλθὼν εἶπεν… ἀναστὰς πορεύσομαι πρὸς τὸν πατέρα μου',
      note: "The prodigal's repentance: 'came to himself' (metanoia = change of mind) then 'arose and went' (shub = return). True repentance always moves toward the Father.",
    },
    {
      reference: 'Hosea 6:1',
      english: '"Come, let us return [shub] to the LORD. He has torn us to pieces but he will heal us."',
      greek: 'לְכוּ וְנָשׁוּבָה אֶל-יְהוָה כִּי הוּא טָרַף וְיִרְפָּאֵנוּ',
      note: "The OT shub pattern: God disciplines to create the longing to return. The wound and the healing come from the same hand — return is always welcomed.",
    },
  ],
  prayer: [
    {
      reference: 'Matthew 6:9–13',
      english: '"Our Father in heaven, hallowed be your name, your kingdom come…"',
      greek: 'Πάτερ ἡμῶν ὁ ἐν τοῖς οὐρανοῖς· ἁγιασθήτω τὸ ὄνομά σου· ἐλθέτω ἡ βασιλεία σου',
      note: "The Lord's Prayer (proseuchē) begins with God's name, kingdom, and will — not human needs. The structure teaches the order of priority in prayer.",
    },
    {
      reference: 'Romans 8:26',
      english: '"The Spirit himself intercedes for us through wordless groans."',
      greek: 'αὐτὸ τὸ πνεῦμα ὑπερεντυγχάνει στεναγμοῖς ἀλαλήτοις',
      note: "When we cannot pray, the pneuma prays in us — with inarticulate groans (stenagmois alalētois). Prayer is not only our words toward God but God's Spirit praying through us.",
    },
    {
      reference: 'Psalm 62:8',
      english: '"Trust in him at all times, you people; pour out your hearts to him, for God is our refuge."',
      greek: 'בִּטְחוּ בוֹ בְכָל-עֵת עָם שִׁפְכוּ-לְפָנָיו לְבַבְכֶם',
      note: "'Pour out your hearts' — tephillah is not polished religious speech but the unfiltered contents of the lev (heart) brought before God.",
    },
  ],
  power: [
    {
      reference: 'Acts 1:8',
      english: '"You will receive power [dynamin] when the Holy Spirit comes on you; and you will be my witnesses."',
      greek: 'ἀλλὰ λήμψεσθε δύναμιν ἐπελθόντος τοῦ ἁγίου πνεύματος ἐφ᾽ ὑμᾶς',
      note: "The dynamis comes from the pneuma — not from human organization, charisma, or strategy. Witness is impossible without power, but the power is given, not manufactured.",
    },
    {
      reference: 'Matthew 28:18',
      english: '"All authority [exousia] in heaven and on earth has been given to me."',
      greek: 'ἐδόθη μοι πᾶσα ἐξουσία ἐν οὐρανῷ καὶ ἐπὶ γῆς.',
      note: "Exousia (authority/right) — given to the risen Christ. The Great Commission flows from this: because all exousia belongs to Jesus, his people go everywhere in his name.",
    },
    {
      reference: 'Isaiah 40:29–31',
      english: '"He gives strength [koach] to the weary… but those who hope in the LORD will renew their strength [koach]."',
      greek: 'נֹתֵן לַיָּעֵף כֹּחַ… וְקוֹיֵ יְהוָה יַחֲלִיפוּ כֹחַ',
      note: "The koach exchange: human strength is finite and exhaustible; divine koach renews. 'Renew' (yachaliph) means to exchange — giving your weakness and receiving God's strength.",
    },
  ],
  joy: [
    {
      reference: 'John 15:11',
      english: '"I have told you this so that my joy [chara] may be in you and that your joy may be complete."',
      greek: 'ταῦτα λελάληκα ὑμῖν ἵνα ἡ χαρὰ ἡ ἐμὴ ἐν ὑμῖν ᾖ καὶ ἡ χαρὰ ὑμῶν πληρωθῇ.',
      note: "Jesus' own chara — the joy of his relationship with the Father — is what he desires for his disciples. The joy is not generated but received; not a target but an overflow.",
    },
    {
      reference: 'Nehemiah 8:10',
      english: '"The joy [simchah] of the LORD is your strength."',
      greek: 'כִּי-חֶדְוַת יְהוָה הִיא מָעֻזְּכֶם',
      note: "Said while the people wept upon hearing the law. God's simchah in his people becomes the source of their strength (maoz). The direction is surprising: not our joy in God but God's joy in us.",
    },
    {
      reference: 'James 1:2',
      english: '"Consider it pure joy [charan], my brothers and sisters, whenever you face trials of many kinds."',
      greek: 'Πᾶσαν χαρὰν ἡγήσασθε, ἀδελφοί μου, ὅταν πειρασμοῖς περιπέσητε ποικίλοις',
      note: "Chara is commanded even in trials — impossible if joy were an emotion. Joy is a choice of orientation toward what God is producing, not a feeling about what is happening.",
    },
  ],
  heart: [
    {
      reference: 'Proverbs 4:23',
      english: '"Above all else, guard your heart [lev], for everything you do flows from it."',
      greek: 'מִכָּל-מִשְׁמָר נְצֹר לִבֶּךָ כִּי-מִמֶּנּוּ תּוֹצְאוֹת חַיִּים',
      note: "The lev as the source (totzeot) of all life — what flows from it determines everything. Guarding the lev is the primary discipline because it governs all others.",
    },
    {
      reference: 'Jeremiah 17:9–10',
      english: '"The heart [lev] is deceitful above all things… but I the LORD search the heart."',
      greek: 'עָקֹב הַלֵּב מִכֹּל וְאָנֻשׁ הוּא… אֲנִי יְהוָה חֹקֵר לֵב',
      note: "The lev's problem: it deceives its own owner. Self-knowledge is limited; only God searches (choqer) the lev completely. The new covenant addresses this — God writes his law on the lev (Jer 31:33).",
    },
    {
      reference: 'Matthew 5:8',
      english: '"Blessed are the pure in heart [kardia], for they will see God."',
      greek: 'μακάριοι οἱ καθαροὶ τῇ καρδίᾳ, ὅτι αὐτοὶ τὸν Θεὸν ὄψονται.',
      note: "Katharos kardia — undivided, single-focused. Kierkegaard: 'Purity of heart is to will one thing.' The pure kardia sees God because it is entirely oriented toward him.",
    },
  ],
  lamb: [
    {
      reference: 'John 1:29',
      english: '"Look, the Lamb [amnos] of God, who takes away the sin of the world!"',
      greek: 'Ἴδε ὁ ἀμνὸς τοῦ Θεοῦ ὁ αἴρων τὴν ἁμαρτίαν τοῦ κόσμου.',
      note: "John the Baptist's announcement fuses three images: the Passover lamb (Exod 12), the sin-bearing scapegoat (Lev 16), and the Servant of Isaiah 53. One amnos fulfills all three.",
    },
    {
      reference: 'Revelation 5:12',
      english: '"Worthy is the Lamb [arnion], who was slain, to receive power and wealth and wisdom and strength and honor and glory and praise!"',
      greek: 'Ἄξιόν ἐστιν τὸ ἀρνίον τὸ ἐσφαγμένον λαβεῖν τὴν δύναμιν',
      note: "The slaughtered arnion receives 7 attributes of divine majesty. Revelation's great reversal: the one who appeared weak and sacrificed is revealed as the cosmic ruler.",
    },
    {
      reference: 'Isaiah 53:7',
      english: '"He was led like a lamb [seh] to the slaughter, and as a sheep before its shearers is silent."',
      greek: 'כְּשֶׂה לַטֶּבַח יוּבַל וּכְרָחֵל לִפְנֵי גֹזְזֶיהָ נֶאֱלָמָה',
      note: "The Servant Song — quoted in Acts 8 to explain Jesus. The seh's silence is not weakness but sovereign submission. The Lamb was not a victim; he 'gave himself up' (Gal 2:20).",
    },
  ],
  shepherd: [
    {
      reference: 'Psalm 23:1–3',
      english: '"The LORD is my shepherd [ro\'eh], I lack nothing. He makes me lie down in green pastures."',
      greek: 'יְהוָה רֹעִי לֹא אֶחְסָר׃ בִּנְאוֹת דֶּשֶׁא יַרְבִּיצֵנִי',
      note: "The most beloved psalm. YHWH as ro'eh covers all needs: rest, restoration, guidance, protection, provision. The sheep's only requirement is to follow.",
    },
    {
      reference: 'John 10:11',
      english: '"I am the good shepherd [poimēn kalos]. The good shepherd lays down his life for the sheep."',
      greek: 'Ἐγώ εἰμι ὁ ποιμὴν ὁ καλός· ὁ ποιμὴν ὁ καλὸς τὴν ψυχὴν αὐτοῦ τίθησιν ὑπὲρ τῶν προβάτων.',
      note: "Kalos = good, beautiful, noble. Jesus is not merely a functional poimēn but a morally beautiful one — the standard by which all leadership is measured.",
    },
    {
      reference: 'Ezekiel 34:11–12',
      english: '"I myself will search for my sheep and look after them… I will rescue them."',
      greek: 'כִּי-כֹה אָמַר אֲדֹנָי יְהוִה הִנְנִי-אֲנִי וְדָרַשְׁתִּי אֶת-צֹאנִי',
      note: "God indicts the false shepherds of Israel (34:1-10) then declares he will shepherd directly. Jesus' 'I am the good shepherd' is the fulfillment of this Ezekiel promise.",
    },
  ],
  name: [
    {
      reference: 'Philippians 2:9–11',
      english: '"God exalted him to the highest place and gave him the name [onoma] that is above every name."',
      greek: 'διὸ καὶ ὁ Θεὸς αὐτὸν ὑπερύψωσεν καὶ ἐχαρίσατο αὐτῷ τὸ ὄνομα τὸ ὑπὲρ πᾶν ὄνομα',
      note: "The 'name above every name' is YHWH — Paul quotes the Shema (Isa 45:23) and applies it to Jesus. The onoma is not the word 'Jesus' but the divine identity it represents.",
    },
    {
      reference: 'Exodus 3:14–15',
      english: '"I AM WHO I AM… This is my name [shem] forever, the name you shall call me from generation to generation."',
      greek: 'אֶהְיֶה אֲשֶׁר אֶהְיֶה… זֶה-שְּׁמִי לְעֹלָם',
      note: "The revelation of the divine shem at the burning bush. YHWH (I AM) is the name — it reveals God's self-existence, faithfulness, and eternal character. Jesus' 'I am' statements echo this.",
    },
    {
      reference: 'Proverbs 18:10',
      english: '"The name [shem] of the LORD is a fortified tower; the righteous run to it and are safe."',
      greek: 'מִגְדַּל-עֹז שֵׁם יְהוָה בּוֹ-יָרוּץ צַדִּיק וְנִשְׂגָּב',
      note: "The shem as shelter — to pray 'in the name of the Lord' is to run into the fortress. The name carries his presence, authority, and protection.",
    },
  ],
  blessing: [
    {
      reference: 'Genesis 12:2–3',
      english: '"I will bless [berakah] you… and all peoples on earth will be blessed through you."',
      greek: 'וַאֲבָרֶכְךָ… וְנִבְרְכוּ בְךָ כֹּל מִשְׁפְּחֹת הָאֲדָמָה',
      note: "The Abrahamic blessing — the original mission statement of Israel. The berakah flows through Abraham to the nations. Paul calls this 'the gospel in advance' (Gal 3:8).",
    },
    {
      reference: 'Ephesians 1:3',
      english: '"Praise be to the God and Father of our Lord Jesus Christ, who has blessed [eulogēsas] us in the heavenly realms with every spiritual blessing."',
      greek: 'Εὐλογητὸς ὁ Θεὸς καὶ πατὴρ τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ, ὁ εὐλογήσας ἡμᾶς ἐν πάσῃ εὐλογίᾳ πνευματικῇ',
      note: "Paul begins the most theologically dense passage in his letters (Eph 1:3-14) with a triple eulogia: God is blessed/praised, he has blessed us, with every blessing. The source and the gift are both eulogia.",
    },
    {
      reference: 'Numbers 6:24–26',
      english: '"The LORD bless you [yevarekekha] and keep you; the LORD make his face shine on you."',
      greek: 'יְבָרֶכְךָ יְהוָה וְיִשְׁמְרֶךָ יָאֵר יְהוָה פָּנָיו אֵלֶיךָ',
      note: "The Aaronic berakah — the oldest recorded blessing in Scripture. Three couplets, each expanding: protection, grace, and shalom. Still spoken in synagogues and churches today.",
    },
  ],
  creation: [
    {
      reference: 'Genesis 1:1',
      english: '"In the beginning God created [bara] the heavens and the earth."',
      greek: 'בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ',
      note: "The first word, Bereshit (In beginning), has no definite article — not 'the beginning' but 'a beginning': creation initiates time itself. Bara (created) is used only of God's action — out of nothing.",
    },
    {
      reference: 'Romans 8:19–22',
      english: '"For the creation [ktisis] waits in eager expectation for the children of God to be revealed."',
      greek: 'ἡ γὰρ ἀποκαραδοκία τῆς κτίσεως τὴν ἀποκάλυψιν τῶν υἱῶν τοῦ Θεοῦ ἀπεκδέχεται.',
      note: "The ktisis has its own longing and suffering — creation is not neutral scenery but a participant in the redemption story. The gospel's scope is cosmic, not just human.",
    },
    {
      reference: '2 Corinthians 5:17',
      english: '"If anyone is in Christ, the new creation [ktisis] has come: the old has gone, the new is here!"',
      greek: 'ὥστε εἴ τις ἐν Χριστῷ, καινὴ κτίσις·',
      note: "Kainos ktisis — not a repaired old thing but a genuinely new creation. The believer participates in the 'already' of the new creation that will be completed at Christ's return.",
    },
  ],
  eternal: [
    {
      reference: 'John 17:3',
      english: '"Now this is eternal life [aiōnios zōē]: that they know you, the only true God, and Jesus Christ, whom you have sent."',
      greek: 'αὕτη δέ ἐστιν ἡ αἰώνιος ζωή, ἵνα γινώσκωσίν σε τὸν μόνον ἀληθινὸν Θεόν',
      note: "Jesus defines aiōnios zōē not as endless duration but as a relationship: knowing (ginōskōsin — ongoing, present tense) the Father and Son. Eternal life begins at belief, not death.",
    },
    {
      reference: 'Psalm 90:2',
      english: '"Before the mountains were born… from everlasting to everlasting [me-olam ad-olam] you are God."',
      greek: 'מֵעוֹלָם עַד-עוֹלָם אַתָּה אֵל',
      note: "Moses' prayer — olam in both directions: eternal past and eternal future. God is not in time; time is in God. All creation and history are bounded by his olam.",
    },
    {
      reference: 'Daniel 12:2',
      english: '"Multitudes who sleep in the dust of the earth will awake: some to everlasting [olam] life, others to shame and everlasting contempt."',
      greek: 'וְרַבִּים מִיְּשֵׁנֵי אַדְמַת-עָפָר יָקִיצוּ אֵלֶּה לְחַיֵּי עוֹלָם וְאֵלֶּה לַחֲרָפוֹת לְדִרְאוֹן עוֹלָם',
      note: "The clearest OT statement of resurrection and olam life. The same olam applies to both destinies — eternal blessing and eternal shame are equally permanent.",
    },
  ],
  servant: [
    {
      reference: 'Isaiah 53:11',
      english: '"After he has suffered, he will see the light of life and be satisfied; by his knowledge my righteous servant [eved] will justify many."',
      greek: 'יִרְאֶה מֵעֲמַל נַפְשׁוֹ יִשְׂבָּע בְּדַעְתּוֹ יַצְדִּיק צַדִּיק עַבְדִּי לָרַבִּים',
      note: "The eved Yahweh's suffering is not defeat but the means of justifying 'many.' The Servant Songs (Isa 42, 49, 50, 53) reach their climax here: suffering that accomplishes redemption.",
    },
    {
      reference: 'Mark 10:44–45',
      english: '"Whoever wants to be first must be slave [doulos] of all. For even the Son of Man did not come to be served, but to serve."',
      greek: 'καὶ ὃς ἂν θέλῃ ἐν ὑμῖν εἶναι πρῶτος ἔσται πάντων δοῦλος· καὶ γὰρ ὁ υἱὸς τοῦ ἀνθρώπου',
      note: "Jesus redefines greatness: the first is the doulos of all. He grounds the ethic in his own identity — 'even the Son of Man' is a servant.",
    },
    {
      reference: 'Philippians 2:7',
      english: '"Rather, he made himself nothing by taking the very nature of a servant [doulos], being made in human likeness."',
      greek: 'ἀλλ᾽ ἑαυτὸν ἐκένωσεν μορφὴν δούλου λαβών, ἐν ὁμοιώματι ἀνθρώπων γενόμενος',
      note: "Kenōsis — the self-emptying. The eternal Son took on the morphē (form/essence) of a doulos. He did not play at servanthood; he became it.",
    },
  ],
  wrath: [
    {
      reference: 'Romans 1:18',
      english: '"The wrath [orgē] of God is being revealed from heaven against all the godlessness and wickedness of people."',
      greek: 'ἀποκαλύπτεται γὰρ ὀργὴ Θεοῦ ἀπ᾽ οὐρανοῦ ἐπὶ πᾶσαν ἀσέβειαν καὶ ἀδικίαν ἀνθρώπων',
      note: "Orgē is present-tense, present-active: the wrath of God 'is being revealed' — it is not a future event but an ongoing reality expressed in the moral order of consequences.",
    },
    {
      reference: 'Nahum 1:2–3',
      english: '"The LORD is a jealous and avenging God… slow to anger but great in power; the LORD will not leave the guilty unpunished."',
      greek: 'אֵל קַנּוֹא וְנֹקֵם יְהוָה… אֶרֶךְ אַפַּיִם וּגְדָל-כֹּחַ וְנַקֵּה לֹא יְנַקֶּה יְהוָה',
      note: "The aph of God is never arbitrary: he is 'slow to anger' (erek apayim = long of nostril). God's wrath is the last resort, not the first impulse.",
    },
    {
      reference: 'Revelation 6:16–17',
      english: '"Fall on us and hide us from the face of him who sits on the throne and from the wrath [orgē] of the Lamb!"',
      greek: 'καὶ λέγουσιν τοῖς ὄρεσιν καὶ ταῖς πέτραις· πέσετε ἐφ᾽ ἡμᾶς… ἀπὸ τῆς ὀργῆς τοῦ ἀρνίου',
      note: "The 'wrath of the Lamb' — the most jarring phrase in Revelation. The arnion who absorbs wrath at the cross becomes the source of judgment at the end. Gentleness and justice are the same person.",
    },
  ],
  blood: [
    {
      reference: 'Hebrews 9:22',
      english: '"Without the shedding of blood [haimatos], there is no forgiveness."',
      greek: 'χωρὶς αἱματεκχυσίας οὐ γίνεται ἄφεσις.',
      note: "Haima + ekchysis (shedding) — the most direct statement of atonement theology. Life for life: sin's cost is death; forgiveness requires a death paid by another.",
    },
    {
      reference: 'Exodus 12:13',
      english: '"The blood [dam] will be a sign for you… when I see the blood, I will pass over you."',
      greek: 'וְהָיָה הַדָּם לָכֶם לְאֹת… וְרָאִיתִי אֶת-הַדָּם וּפָסַחְתִּי עֲלֵכֶם',
      note: "The Passover — the dam protects not because of the quality of the people inside but because of the blood on the door. The protective power is entirely in the dam, not in the one sheltering under it.",
    },
    {
      reference: '1 John 1:7',
      english: '"The blood [haima] of Jesus, his Son, purifies us from all sin."',
      greek: 'τὸ αἷμα Ἰησοῦ τοῦ υἱοῦ αὐτοῦ καθαρίζει ἡμᾶς ἀπὸ πάσης ἁμαρτίας.',
      note: "Katharizei — present tense, continuous: 'keeps on cleansing.' The haima of Christ is not a one-time legal transaction but an ongoing cleansing reality for those walking in the light.",
    },
  ],
}
